version: '2'
services:
  car-admin:
    image: car/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  car-api:
    image: car/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev